site_name: NativeStrapper
site_description: A cross-platform Roblox bootstrapper
site_url: https://nativestrapper.gitlab.io

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - navigation.top

nav:
  - Home: index.md
  - Writing Scripts:
    - Overview: scripts/index.md
    - metadata table: scripts/metadata.md
    - API Reference: scripts/api.md